# Site settings
name: Yujie_Yang's BLOG
email: 615851120@qq.com
author: Yujie_Yang
url: https://okcthouder.github.io/Yujie_Yang.github.io/index.html
resume_site: https://okcthouder.github.io/Yujie_Yang.github.io/
github: https://github.com/OKCthouder/
baseurl: ""
description: 一枚小小前端程序员。
meta_description: 杨宇杰;个人博客;学而不思则罔;思而不学则殆;生命不止;折腾不休
motto: No pains,no gains.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: OKCthouder
highlighter: Pygments

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9
gems: [jekyll-paginate]
FB:
  comments :
    provider : duoshuo
    duoshuo:
        short_name : luoyan35714
    disqus :
        short_name : freudkang
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light